spring:
  application:
    name: zipkin-server
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  metrics:
    web:
      server:
        auto-time-requests: false