spring:
  application:
    name: user
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
