server:
  port: 8085
spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/beauthes/configserver.git
          username: 1025521973@qq.com
          password: ren19961030
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  sleuth:
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    enabled: true
#    locator:
#      discovery:
#        enabled: true
#    sender:
#      type: web
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
management:
  endpoints:
    web:
      exposure:
        include: "*"

