#foo: test123
#server:
#  port: 8081
#spring:
#  application:
#    name: user-dao
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: hrt@2019
#    url: jdbc:mysql://47.92.3.103:3306/kac_test?useSSL=false
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  sleuth:
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    enabled: true
#    locator:
#      discovery:
#        enabled: true
#    sender:
#      type: web
#management:
#  endpoints:
#    web:
#      base-path: /
#      exposure:
#        include: "*"
#eureka:
#  client:
#    service-url:
#      defaultZone: http://user:password@localhost:8761/eureka
#  instance:
#    lease-renewal-interval-in-seconds: 5
#    prefer-ip-address: true